anomstack/jobs/score.py, anomstack/jobs/train.py, metrics/defaults/defaults.yaml, metrics/defaults/python/preprocess.py, metrics/defaults/sql/score.sql
previously was just scoring the most recent metric value but now it should score all non scored values from recent data.
=> fix score to score all thats needed

anomstack/jobs/ingest.py, anomstack/jobs/plot.py, anomstack/main.py, metrics/defaults/defaults.yaml, metrics/defaults/sql/plot.sql, metrics/examples/bigquery/bigquery_example_simple/bigquery_example_simple.yaml, metrics/examples/weather/weather.yaml, requirements.txt
add a plot job that will log a plot for each metric batch of values vs scores. 
useful for if you want to eyeball recent metric and scores from within dagster.
=> add a plot job

anomstack/jobs/llmalert.py, anomstack/llm/completion.py, requirements.txt
This pull request updates the openai package to version 1.2.4, which includes bug fixes and performance improvements. The `get_completion` function has been updated to use the new `OpenAI` class instead of the deprecated `openai.ChatCompletion` method. No other changes have been made.
=> Update openai to latest sdk

README.md, anomstack/jobs/alert.py
This pull request adds Alert Saving features to Anomstack.
The Alert Saving feature saves anomaly scores and alerts to a database for querying and further analysis.
=> Add Alert Saving features

.vscode/settings.json, metrics/examples/eirgrid/README.md, metrics/examples/eirgrid/eirgrid.py, metrics/examples/eirgrid/eirgrid.yaml, requirements-dev.txt
Adds a new example called EirGrid. The EirGrid example includes a custom Python ingest function that retrieves current electricity demand metrics from the EirGrid Smart Dashboard API. The function is implemented in the `eirgrid.py` file. This PR aims to improve the project's functionality and provide a practical example for data ingestion.
=> Add EirGrid example

anomstack/main.py, tests/test_main.py
In this pull request, we are commenting out the failure sensors until they are fixed. Additionally, we are adding unit tests for jobs and schedules to ensure their functionality. This will help improve the overall reliability and stability of the codebase.
=> Comment out failure sensors and add unit tests for jobs and schedules

anomstack/jobs/plot.py, anomstack/plots/plot.py, dashboard.py, metrics/defaults/defaults.yaml, metrics/defaults/sql/dashboard.sql, metrics/defaults/sql/plot.sql
This pull request adds a new column called "metric_change" to the Plot SQL query. The "metric_change" column is used to track changes in the metric value. This change allows for the creation of a scatter plot for metric changes in the batch plot.
Also added to dashboard plots.
=> Add metric change column to Plot SQL query & Dashboard

metrics/defaults/sql/alerts.sql
seems to be some issues with it so disabling it for now
=> disable alert snooze

metrics/defaults/sql/alerts.sql
temp add metric_alert_historic to alerts sql to be able to better validate snooze logic
=> add metric_alert_historic to alerts sql template

.example.env, README.md, anomstack/df/save.py, anomstack/external/sqlite/sqlite.py, anomstack/jinja/render.py, anomstack/jobs/plot.py, anomstack/sql/read.py, docker-compose.yaml, metrics/defaults/defaults.yaml, metrics/defaults/sql/alerts.sql, metrics/defaults/sql/change.sql, metrics/defaults/sql/dashboard.sql, metrics/defaults/sql/plot.sql, metrics/defaults/sql/score.sql, metrics/defaults/sql/summary.sql, metrics/defaults/sql/train.sql, metrics/examples/example_simple/example_simple.yaml, requirements.compile, requirements.txt
This pull request introduces support for SQLite as a new database option in the project. The most important changes include updates to configuration files, documentation, and the addition of helper functions for SQLite.
* [`.example.env`](diffhunk://#diff-9d7a2448bb252b3987e5cbb36d9d9818b1432313d86287acf8140d48ff911cdaR24-R26): Added `ANOMSTACK_SQLITE_PATH` for local SQLite path configuration.
* [`metrics/defaults/defaults.yaml`](diffhunk://#diff-87b1ac24a54e3a83a9a0c5caddafbc2b2e4c8df4cee00ebfe10c73968112b2f7L2-R2): Changed the default database type from DuckDB to SQLite.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L53-R53): Updated SQLite entry to include a link to the new SQLite helper functions and marked it as fully supported. …
=> Add sqlite

anomstack/jobs/plot.py, anomstack/plots/plot.py
This pull request includes several updates to improve the plotting functionality and code readability in the `anomstack` package. The most important changes include adding new imports for date formatting and tick locating, updating the `make_batch_plot` function to handle datetime conversion and improve x-axis formatting, and minor code style adjustments.
* [`anomstack/plots/plot.py`](diffhunk://#diff-5532cf8faa006a5c3ed8e1a9ab7c86e6563b7395408992e1644d65da417a63a5R9-R10): Added imports for `matplotlib.dates` and `matplotlib.ticker` to support date formatting and tick locating.
* [`anomstack/plots/plot.py`](diffhunk://#diff-5532cf8faa006a5c3ed8e1a9ab7c86e6563b7395408992e1644d65da417a63a5R106): Updated `make_batch_plot` function to convert `metric_timestamp` to datetime and set x-axis …
=> Small plotting improvements

anomstack/jobs/score.py, anomstack/jobs/train.py, metrics/defaults/defaults.yaml, metrics/examples/netdata/netdata.yaml
This pull request introduces several changes to the anomaly detection job scripts and configuration files to support multiple models and their combination methods. The most important changes include refactoring the `score` and `train` functions to handle multiple model configurations, updating the configuration files to reflect these changes, and adding new combination methods for model scores.
* [`anomstack/jobs/score.py`](diffhunk://#diff-75a9090780ff4db684849473d4982e62c05857ebfee470de72ceaaa2670ff080L61-R62): Refactored the `score` function to load and predict using multiple models specified in `model_configs`, and combine their scores using a specified method (`model_combination_method`). [[1]](diffhunk://#diff-75a9090780ff4db684849473d4982e62c05857ebfee470de72ceaaa2670ff080L61-R62) …
=> Make list of models

anomstack/alerts/email.py, anomstack/alerts/send.py, anomstack/alerts/slack.py, anomstack/jobs/change.py, anomstack/jobs/score.py, anomstack/plots/plot.py
This pull request enhances the alerting system by adding a customizable `score_title` parameter to various alert functions and their corresponding plot generation functions. This allows for more descriptive titles and labels in the generated plots, improving the clarity of the visualized data.
Key changes include:
* Added `score_title` parameter to `send_email_with_plot` in `anomstack/alerts/email.py` and updated the function to pass this parameter to `make_alert_plot`. [[1]](diffhunk://#diff-4f43c8f3ab4b0c66f241fa99286f3692c19f7fdfd039bff65b8a7e00535851e9R27) [[2]](diffhunk://#diff-4f43c8f3ab4b0c66f241fa99286f3692c19f7fdfd039bff65b8a7e00535851e9R42-R43) [[3]](diffhunk://#diff-4f43c8f3ab4b0c66f241fa99286f3692c19f7fdfd039bff65b8a7e00535851e9L57-R62)
* Added `score_title` parameter to …
=> Clean up change plot labels

anomstack/alerts/asciiart.py, anomstack/alerts/email.py, anomstack/alerts/send.py, anomstack/alerts/slack.py, anomstack/ml/change.py, anomstack/plots/plot.py
This pull request includes several changes to the alerting and plotting functionalities in the `anomstack` package. The most important changes include adding support for tags in various alert functions, making the ASCII graph optional in alert messages, and modifying the alert detection logic.
* [`anomstack/alerts/email.py`](diffhunk://#diff-4f43c8f3ab4b0c66f241fa99286f3692c19f7fdfd039bff65b8a7e00535851e9L27-R28): Added support for `tags` parameter in `send_email_with_plot` function to include additional metadata in email alerts. [[1]](diffhunk://#diff-4f43c8f3ab4b0c66f241fa99286f3692c19f7fdfd039bff65b8a7e00535851e9L27-R28) [[2]](diffhunk://#diff-4f43c8f3ab4b0c66f241fa99286f3692c19f7fdfd039bff65b8a7e00535851e9L61-R62)
* [`anomstack/alerts/send.py`](diffhunk://#diff-e5db777292ca2dc5d9c712c1 …
=> clean up alert msg

anomstack/alerts/slack.py, anomstack/jobs/alert.py, anomstack/plots/plot.py
This pull request includes several updates to improve the functionality and readability of the alerting and plotting systems. The key changes involve modifying alert types, enhancing plot visualizations, and refining logging practices.
* Changed the alert type from "ml" to "anomaly" in the `alert` function to better reflect the nature of the alerts. (`anomstack/jobs/alert.py`)
* Improved the `make_alert_plot` function by adjusting the plot style, marker size, and label for better visualization and clarity. (`anomstack/plots/plot.py`)
* Updated the alert points to use `metric_score` instead of `metric_alert` and added a marker size for better distinction. (`anomstack/plots/plot.py`)
* Changed the vertical line color for alert points from yellow to grey for better visual contrast. …
=> Alert plot cleanup

anomstack/ml/change.py, metrics/defaults/sql/change.sql
This pull request includes changes to enhance the change detection logic and update the SQL queries to reflect the new metric change naming convention. The most important changes include the addition of logging functionality, renaming of metric columns, and updates to SQL queries to align with the new column names.
Enhancements to change detection logic:
* Added `log_df_info` import and set `pd.options.display.max_columns` to 10 in `anomstack/ml/change.py`.
* Updated the `detect_change` function to include additional logging and renamed the `metric_alert` column to `metric_change_calculated`.
Updates to SQL queries:
* Renamed `metric_change_alert` to `metric_change` in the `metrics/defaults/sql/change.sql` file [[1]](diffhunk://#diff-930a2ae9fa8dee5df1ce55b087a4ce10ed5b81a4365ec37725eb1b52 …
=> Clean up change logic further

anomstack/external/sqlite/sqlite.py
This pull request includes changes to the `anomstack/external/sqlite/sqlite.py` file to enhance the reliability of reading from SQLite databases by adding retry logic.
Enhancements to SQLite read function:
* [`read_sql_sqlite`](diffhunk://#diff-bb44a0620fca94c34ebd5f4e88bcad569eb764a359bf754fe2847e4d60b477a7L18-R18): Updated the function to include retry logic when attempting to read from a SQLite database. This involves retrying the connection up to a maximum number of attempts (`MAX_RETRIES`) with a delay (`RETRY_DELAY`) if the database is locked, and logging warnings and errors appropriately. [[1]](diffhunk://#diff-bb44a0620fca94c34ebd5f4e88bcad569eb764a359bf754fe2847e4d60b477a7L18-R18) [[2]](diffhunk://#diff-bb44a0620fca94c34ebd5f4e88bcad569eb764a359bf754fe2847e4d60b477a7R31-R55)
=> Add retry logic for reading from SQLite database

anomstack/jobs/llmalert.py, anomstack/llm/completion.py, metrics/defaults/defaults.yaml, metrics/defaults/python/prompt.py
This pull request includes significant changes to the anomaly detection process in the `anomstack` project. The most important changes include replacing the `get_completion` function with `detect_anomalies`, modifying the `llmalert` function to handle detected anomalies, and updating the prompt generation for anomaly detection. Additionally, there are updates to the configuration and validation of detected anomalies.
* [`anomstack/llm/completion.py`](diffhunk://#diff-5bd8deb865f4959c80b827d76c0cd6b6de2bb446a8900175557af3355f23b8d0L2-R98): Replaced the `get_completion` function with `detect_anomalies` to detect anomalies using the OpenAI API. Added new classes `Anomaly` and `DetectAnomaliesResponse` for structured anomaly detection responses.
* …
=> Llm refactor

setup.py
This pull request includes a version update for the `anomstack` package in the `setup.py` file.
* [`setup.py`](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L11-R11): Updated the version from `0.0.15` to `0.0.16`.
=> Bump package version to 0.0.16

dashboard/components/toolbar.py, dashboard/routes/batch.py
This pull request focuses on improving the user interface of the anomaly detection dashboard by removing unnecessary buttons, enhancing responsiveness for smaller screens, and improving table layout and readability. Below are the most important changes grouped by theme:
* Removed the "View project on GitHub" button from the toolbar in `dashboard/components/toolbar.py` to simplify the interface.
* Updated the `metric_name` column in `dashboard/routes/batch.py` to include truncation and tooltips for better display on smaller screens.
* Adjusted the feedback buttons (`thumbs-up` and `thumbs-down`) to have dynamic padding and icon sizes for better usability on smaller devices.
* Made the anomaly table in `dashboard/routes/batch.py` more responsive by modifying column widths and adding a …
=> Anomaly list mob

.replit, anomstack/external/duckdb/duckdb.py, dashboard/app.py, dashboard/routes/index.py, dashboard/state.py
This pull request introduces several enhancements and fixes across multiple files, focusing on improving database handling, environment validation, lazy loading, and application startup behavior. Key changes include switching to port 8080 for the dashboard, adding fallback mechanisms for database connections, implementing lazy initialization for app state components, and introducing health check endpoints for faster startup.
* [`.replit`](diffhunk://#diff-dabe747bc6b60b9f68c11dfbf2fbc44d3d37bd289e8f7fdc88647cd697d5cbaeL8-R16): Changed `localPort` from 80 to 8080 and updated workflow settings to reflect the new port. Added `REPLIT_WEBVIEW_PORT` environment variable for consistency. [[1]](diffhunk://#diff-dabe747bc6b60b9f68c11dfbf2fbc44d3d37bd289e8f7fdc88647cd697d5cbaeL8-R16) …
=> Fixdeploy2

anomstack/jobs/alert.py, anomstack/jobs/change.py, anomstack/jobs/llmalert.py
This pull request introduces improvements to error handling and data processing in the alerting workflows across multiple modules (`alert.py`, `change.py`, and `llmalert.py`). The key changes include wrapping alert-sending operations in `try-except` blocks to prevent failures from blocking subsequent operations and explicitly selecting columns during DataFrame processing to ensure type consistency.
* **`alert.py`, `change.py`, and `llmalert.py`:** Added `try-except` blocks around `send_alert` calls to ensure that failures in sending alerts do not interrupt the processing of other metrics. Logging was added to record success or failure for each alert. [[1]](diffhunk://#diff-f2d86b49c85b65a8c50540f468038a896887ee19e69757f21fc4292510c444cbR122-R124) …
=> Enhance alert handling by wrapping send_alert calls in try-except blocks

tests/README.md
- Revised README.md to provide a concise overview of the anomstack test suite, including a quick start guide and detailed test categories.
- Enhanced coverage report section to reflect improvements and provide clearer insights into test coverage across modules.
- Added new test files for email notifications, ASCII art generation, and DuckDB operations, contributing to overall code coverage of 63%.
- Streamlined commands for running tests and generating coverage reports, improving usability for developers.
=> Update test suite documentation and structure for clarity and coverage

anomstack/jobs/llmalert.py, anomstack/llm/agent.py, metrics/defaults/defaults.yaml, tests/test_llm.py
This pull request introduces significant enhancements to the anomaly detection system by adding support for customizable detection and verification prompts, improving logging for debugging purposes, and updating the prompt extraction logic. Additionally, it includes tests to ensure the correctness of the new functionality.
* [`anomstack/jobs/llmalert.py`](diffhunk://#diff-4e6d1eb6b2e6327eec1e17ee3c455309a8efdad5d40f86f4ff763639e763ce18L68-R74): Added support for both detection and verification prompts, allowing backward compatibility with legacy `system_prompt`. Updated the anomaly detection function to use these prompts, with fallback to defaults if unspecified. [[1]](diffhunk://#diff-4e6d1eb6b2e6327eec1e17ee3c455309a8efdad5d40f86f4ff763639e763ce18L68-R74) …
=> Enhance anomaly detection prompts

.devcontainer/README.md, .devcontainer/devcontainer.dev.json, .devcontainer/initialize.sh, Makefile, docker/Dockerfile.anomstack_code, docker/Dockerfile.anomstack_dashboard
This pull request introduces enhancements to the development environment and Docker configurations for `anomstack`. Key changes include adding documentation for devcontainer setups, creating a new development-specific devcontainer configuration, updating initialization scripts, and improving Dockerfile dependencies and Makefile commands.
* [`.devcontainer/README.md`](diffhunk://#diff-0f9548cbce10dbdef0b86d783ed0727a4ac1061fc71cb549b5dbd400705c71fdR1-R81): Added detailed documentation for devcontainer configurations, including usage instructions for GitHub Codespaces and VS Code Dev Containers, and a comparison of features between `devcontainer.json` (User/Demo) and `devcontainer.dev.json` (Development).
* [`.devcontainer/devcontainer.dev.json`](diffhunk://#diff-474860469596eabdce5e16e8a5af …
=> Enhance development setup with new Docker and Makefile features

dashboard/app.py, dashboard/routes/index.py
This pull request introduces health check endpoints to improve deployment monitoring and updates the application startup logic for better error handling. The existing health check route in `index.py` has been removed, as it is now replaced by the new implementation in `app.py`.
* [`dashboard/app.py`](diffhunk://#diff-ea8585cc482637297ded23c1672137835305d82aea8e223a8a8c3a9aede6e58bR57-R87): Added a `/health` endpoint for a quick health check and a root (`/`) handler to respond to Cloud Run and Kubernetes health probes. The root handler distinguishes between health check requests and normal user requests based on the `User-Agent` header.
* [`dashboard/routes/index.py`](diffhunk://#diff-81e2c3a8005abb6d4b9d6dfcb9054df0de959f9b73913398604dd968276a7180L208-L211): Removed the previous `/health` …
=> Fixdeploy20250715

docs/docs/configuration/environment-variables.md, docs/docs/miscellaneous/scripts-utilities.md, docs/docs/quickstart.md, docs/package-lock.json, docs/package.json, docs/sidebars.js, docs/src/components/HomepageFeatures/index.js, docs/src/pages/index.js, docs/yarn.lock
- Upgraded Docusaurus dependencies to version 3.8.1 for improved performance and features.
- Enhanced the Quickstart guide with Docker setup instructions for easier deployment.
- Added new sections for supported data sources and deployment options on the homepage.
- Improved the feature list with detailed descriptions of Anomstack's capabilities.
- Updated sidebar to include new configuration and utility scripts documentation.
- Cleaned up package-lock and yarn.lock files to reflect the latest dependency versions.
GIT_VALID_PII_OVERRIDE
This pull request introduces comprehensive documentation for environment variables and utility scripts in Anomstack. The changes provide detailed guidance on configuring the application, managing databases, performing administrative tasks, and …
=> feat: Update documentation and configuration for Anomstack
