andrewm4894/anomstack

.pre-commit-config.yaml, CONTRIBUTING.md, Makefile, README.md
Hi, 
Had some time to poke around Anomstack and thought I would add a few quick things for housekeeping like pre-commit and a generic contribution guideline file. Let me know if what I have added aligns with you :) 
Used this contribution file as inspiration https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md in case you wanna cherry pick more 
Few things I would add next, I couldn't easily figure out what version of python the project supports without going through the Dockerfile, etc. and maybe as a next PR I was thinking to add pyproject.toml along with poetry to pin the pkgs and make Anomstack an installable package for local development. What do you think?
=> chore: housekeeping using precommit and generic contributing guidelines

metrics/examples/gsod/gsod.sql
This pull request updates the date filter in the gsod.sql file. Previously, the filter was set to select data from 4 days ago, but now it has been updated to select data from 5 days ago. This change ensures that the correct data is being retrieved for analysis.
=> Update date filter in gsod.sql

anomstack/jobs/score.py
This pull request adds error handling for the case when the model is not found. If the model is not found, a warning message is logged and the process continues without loading the model. This prevents the job from failing when a model is missing.
=> Handle if model is not found

dashboard.py
This pull request adds a cache expiration time to the `get_data` function in order to improve performance. Additionally, it adds a button to show the SQL query used to retrieve the data.
=> Add cache expiration time to get_data function and button to show SQL

README.md, anomstack/jobs/alert.py, metrics/defaults/defaults.yaml, metrics/examples/bigquery/bigquery_example_simple/bigquery_example_simple.yaml
This pull request adds the functionality to include custom metric tags in the build_alert_job function. The metric_tags parameter allows for more complex alert routing based on tags such as priority or subject area. This feature enhances the flexibility and customization of the alert system. The changes include modifications to the build_alert_job function, defaults.yaml, bigquery_example_simple.yaml, and the feature list. The pull request also includes updates to the documentation and comments to reflect the new functionality.
=> Add metric tags functionality

anomstack/jobs/alert.py, anomstack/jobs/change.py, setup.py
This pull request refactors the `metric_tags` function to handle missing values. Previously, the function would throw an error if a metric name was not found in the `metric_tags` dictionary. This PR updates the function to use the `get` method to handle missing values gracefully, by returning an empty dictionary instead. This improves the overall robustness and reliability of the code.
=> Refactor metric_tags to handle missing values

metrics/defaults/defaults.yaml
This pull request updates the model training and scoring parameters in the configuration file. Specifically, it increases the maximum number of observations for training a model from 1000 to 2500, and the maximum number of observations for scoring from 20 to 25. It also adjusts the thresholds for anomaly detection and change detection.
=> Update model training and scoring parameters

README.md, metrics/defaults/defaults.yaml, metrics/defaults/sql/alerts.sql
This pull request adds the ability to snooze alerts for a period of time, reducing repeated and duplicate alerts. It includes the following commits:
- Add alert_snooze_n parameter to defaults.yaml
- Handle `alert_snooze_n` in alerts.sql template
- Add ability to snooze alerts to feature list
=> Add ability to snooze alerts

metrics/examples/netdata_httpcheck/netdata_httpcheck.py, metrics/examples/netdata_httpcheck/netdata_httpcheck.yaml, tests/test_main.py
This pull request adds an example for ingesting data from the Netdata API using the `netdata_httpcheck` metric batch. The example includes a Python script that retrieves data from multiple Netdata hosts and charts, and transforms it into a pandas DataFrame. The DataFrame is then cleaned and formatted before being returned. This example can be used as a reference for ingesting Netdata metrics into other systems or performing further analysis.
=> Add netdata httpcheck example

metrics/defaults/sql/alerts.sql
This pull request adds a window function to check for previous alerts within the last `alert_snooze_n` values. It also updates the `metric_alert_calculated` column to only alert if the metric has not been alerted on in the last `alert_snooze_n` values.
=> Add alert snooze functionality

Makefile, docs/docs/graphql/README.md, docs/docs/graphql/examples/start_schedule.md, docs/sidebars.js
This pull request adds documentation and examples for GraphQL to enable multiple jobs in one API call. It includes the following commits:
- Add graphql examples to enable multiple jobs in one api call
- Add GraphQL documentation
- Add GraphQL example to sidebars.js
- Add 'docs' target to Makefile
=> Add GraphQL documentation and examples

anomstack/alerts/email.py, anomstack/alerts/send.py, anomstack/jobs/summary.py, anomstack/main.py, metrics/defaults/defaults.yaml, metrics/defaults/sql/summary.sql, tests/test_main.py
Sends a daily summary of metrics, scores and alerts.
This commit adds a new function called `send_df` to the `send.py` file in the `anomstack.alerts` module. The `send_df` function allows sending alerts with a DataFrame using the specified alert methods, such as email and Slack. The function takes a title, a DataFrame, and optional parameters like alert methods and description. It converts the DataFrame to HTML and sends the alert using the specified methods.
=> Add metric summary email functionality

anomstack/external/aws/s3.py, anomstack/external/gcp/gcs.py, anomstack/io/save.py, anomstack/jobs/train.py, anomstack/ml/train.py, metrics/defaults/defaults.yaml
This pull request introduces changes to the model saving and training processes across multiple storage backends (S3, GCS, and local) to include a `model_tag` attribute. This ensures that models are saved with a more descriptive filename that includes the tag.
* [`anomstack/external/aws/s3.py`](diffhunk://#diff-74a4a8bc8e38f90c74853f187167d6ee60e03d57d6456798ac807668c670b285L49-R68): Updated `save_models_s3` function to include `model_tag` in the model filenames and the list of models to be saved.
* [`anomstack/external/gcp/gcs.py`](diffhunk://#diff-d8e6a65a95cbb8981a51c1bbcc8287eeeeed2d8f997ee90e3626e0dfd4cc64c8L53-R63): Updated `save_models_gcs` function to include `model_tag` in the model filenames and the list of models to be saved. …
=> include model tags as groundwork for suporting multiple models

anomstack/external/aws/s3.py, anomstack/external/gcp/gcs.py, anomstack/io/load.py, anomstack/io/save.py, anomstack/jobs/score.py
This pull request introduces changes to support loading models with an additional `model_tag` parameter across various storage backends (S3, GCS, and local). The main changes include updating function signatures and modifying how model file names are constructed.
* [`anomstack/external/aws/s3.py`](diffhunk://#diff-74a4a8bc8e38f90c74853f187167d6ee60e03d57d6456798ac807668c670b285L81-R106): Updated `load_model_s3` function to include `model_tag` parameter and modified model file naming to incorporate the tag.
* [`anomstack/external/gcp/gcs.py`](diffhunk://#diff-d8e6a65a95cbb8981a51c1bbcc8287eeeeed2d8f997ee90e3626e0dfd4cc64c8L85-R89): Updated `load_model_gcs` function to include `model_tag` parameter and modified model file naming to incorporate the tag. …
=> Add model tag for scores

README.md, anomstack/jobs/plot.py, metrics/examples/README.md, metrics/examples/python/README.md, metrics/examples/python/python_ingest_simple/ingest.py, tests/test_main.py
This pull request includes several changes across multiple files to enhance logging, improve documentation, and add functionality for generating random metrics data with anomalies. The most important changes are detailed below:
* Added `get_dagster_logger` to `anomstack/jobs/plot.py` for improved logging capabilities.
* Implemented a check for empty data frames in `make_plot` function and added logging for cases with no data to plot. [[1]](diffhunk://#diff-bdf291ba71c2cc5455801cde606f02ec7c2f60af44cac703e097874b4678b2ddR101-R102) [[2]](diffhunk://#diff-bdf291ba71c2cc5455801cde606f02ec7c2f60af44cac703e097874b4678b2ddR112-R115)
* Updated `README.md` in `metrics/examples/` to include a comprehensive list of example metric batches.
* Corrected a typo in `metrics/examples/python/README.md`.
* …
=> Make python random

metrics/defaults/defaults.yaml, metrics/defaults/sql/change.sql, metrics/examples/netdata/netdata.yaml, metrics/examples/python/python_ingest_simple/python_ingest_simple.yaml
This pull request includes several updates to the `metrics/defaults/defaults.yaml` file to enhance configuration options, particularly for model parameters, alerting, change detection, and scheduling. Additionally, there are changes to SQL templates and example configurations to support these enhancements.
* Added new sections for model parameters, alert parameters, change detection parameters, and other configurations in `metrics/defaults/defaults.yaml`. These include settings for preprocessing, alert methods, change detection, and rounding of metric values. [[1]](diffhunk://#diff-87b1ac24a54e3a83a9a0c5caddafbc2b2e4c8df4cee00ebfe10c73968112b2f7R4-R7) [[2]](diffhunk://#diff-87b1ac24a54e3a83a9a0c5caddafbc2b2e4c8df4cee00ebfe10c73968112b2f7L18-R69) …
=> ability to include/exclude specific metrics in change detection

metrics/defaults/sql/change.sql
This pull request includes changes to the `metrics/defaults/sql/change.sql` file to handle null values in the metric calculations. The main changes involve using the `ifnull` function to ensure that null values are treated as zero.
Changes to handle null values:
* [`metrics/defaults/sql/change.sql`](diffhunk://#diff-930a2ae9fa8dee5df1ce55b087a4ce10ed5b81a4365ec37725eb1b52781b50c4L45-R45): Modified the `max(metric_value)` calculation to use `max(ifnull(metric_value,0))` to handle null values.
* [`metrics/defaults/sql/change.sql`](diffhunk://#diff-930a2ae9fa8dee5df1ce55b087a4ce10ed5b81a4365ec37725eb1b52781b50c4L76-R76): Changed the `metric_change` alias to use `ifnull(metric_change_alert_data.metric_change,0)` to ensure null values are treated as zero.
=> Fix SQL queries to handle null metric values by using ifnull function

anomstack/df/utils.py, anomstack/external/sqlite/sqlite.py
This pull request includes several changes to the `anomstack` project, focusing on improving logging and adding retry logic for database operations. The most important changes include adding retry logic to the `save_df_sqlite` function, importing necessary modules, and improving the logging setup.
Enhancements to database operations:
* Added retry logic to the `save_df_sqlite` function to handle `sqlite3.OperationalError` when the database is locked. This includes setting `MAX_RETRIES` and `RETRY_DELAY` constants, and implementing a retry loop with logging for each attempt. (`anomstack/external/sqlite/sqlite.py`)
* Imported the `time` module to support the retry delay functionality. (`anomstack/external/sqlite/sqlite.py`)
Logging improvements:
* Improved the logging setup by ensuring the …
=> Enhance SQLite save function with retry logic for locked database errors

.example.env, anomstack/alerts/email.py, anomstack/external/sqlite/sqlite.py, anomstack/jobs/llmalert.py, anomstack/llm/completion.py, metrics/defaults/sql/plot.sql, metrics/examples/python/python_ingest_simple/ingest.py, metrics/examples/python/python_ingest_simple/python_ingest_simple.yaml
This pull request includes several updates to improve the functionality and reliability of the system. The key changes involve updating the OpenAI model, adding a timeout to the SMTP connection, enhancing logging, and refining the handling of database locks and metric data.
* Updated the default OpenAI model to `gpt-4o-mini` in `.example.env` and `anomstack/llm/completion.py` files. This change includes adding a new constant `DEFAULT_OPENAI_MODEL` and logging the model being used. [[1]](diffhunk://#diff-9d7a2448bb252b3987e5cbb36d9d9818b1432313d86287acf8140d48ff911cdaL70-R71) [[2]](diffhunk://#diff-5bd8deb865f4959c80b827d76c0cd6b6de2bb446a8900175557af3355f23b8d0R10-R14) [[3]](diffhunk://#diff-5bd8deb865f4959c80b827d76c0cd6b6de2bb446a8900175557af3355f23b8d0L30-R36)
* Added a timeout …
=> Ressurect llm allert, update to gpt4omini

anomstack/alerts/asciiart.py, anomstack/jobs/llmalert.py, metrics/defaults/defaults.yaml, metrics/defaults/python/prompt.py, metrics/defaults/sql/llmalert.sql, requirements.compile, requirements.txt
This pull request includes several changes focused on improving the LLM alert system and refining the alert message generation. The most important changes involve modifying the alert configuration, updating SQL templates, and enhancing the prompt generation.
* [`anomstack/jobs/llmalert.py`](diffhunk://#diff-4e6d1eb6b2e6327eec1e17ee3c455309a8efdad5d40f86f4ff763639e763ce18L61-R61): Modified the rounding logic for `llmalert_metric_rounding` to allow for no rounding when set to -1, changed the SQL template reference to `llmalert_sql`, and adjusted the handling of missing values in `df_metric`. [[1]](diffhunk://#diff-4e6d1eb6b2e6327eec1e17ee3c455309a8efdad5d40f86f4ff763639e763ce18L61-R61) [[2]](diffhunk://#diff-4e6d1eb6b2e6327eec1e17ee3c455309a8efdad5d40f86f4ff763639e763ce18L80-R80) …
=> Simplify llm

.example.env, metrics/defaults/sql/alerts.sql
This pull request includes changes to the `.example.env` file and significant modifications to the `metrics/defaults/sql/alerts.sql` file to improve SQL query readability and consistency. The most important changes include adding a new environment variable, updating SQL syntax for consistency, and refining the alert calculation logic.
* [`.example.env`](diffhunk://#diff-9d7a2448bb252b3987e5cbb36d9d9818b1432313d86287acf8140d48ff911cdaR77): Added `DAGSTER_HOME` environment variable.
* [`metrics/defaults/sql/alerts.sql`](diffhunk://#diff-722ec27fd20334c84a649c0ef8a19b95b3a190d03d148562c1b277574dbe9bfbR3-R120): Updated SQL keywords to lowercase for consistency and readability.
* [`metrics/defaults/sql/alerts.sql`](diffhunk://#diff-722ec27fd20334c84a649c0ef8a19b95b3a190d03d148562c1b277574dbe9bf …
=> Debug alerts

metrics/defaults/defaults.yaml, metrics/defaults/sql/alerts.sql, metrics/defaults/sql/score.sql, metrics/defaults/sql/train.sql, metrics/examples/eirgrid/eirgrid.yaml
This pull request introduces several enhancements to the metrics processing system, primarily focusing on excluding specific metrics from various stages such as training, scoring, and alerting. The most important changes include updates to the configuration files and SQL templates to support these exclusions.
* [`metrics/defaults/defaults.yaml`](diffhunk://#diff-87b1ac24a54e3a83a9a0c5caddafbc2b2e4c8df4cee00ebfe10c73968112b2f7R31-R36): Added optional lists for excluding metrics from training, scoring, and alerts. [[1]](diffhunk://#diff-87b1ac24a54e3a83a9a0c5caddafbc2b2e4c8df4cee00ebfe10c73968112b2f7R31-R36) [[2]](diffhunk://#diff-87b1ac24a54e3a83a9a0c5caddafbc2b2e4c8df4cee00ebfe10c73968112b2f7R49-R51)
* [`metrics/defaults/sql/alerts.sql`](diffhunk://#diff-722ec27fd20334c84a649c0ef8a19b95b3a …
=> Add train alert score exclude metrics

setup.py
This pull request includes a version update for the `anomstack` package in the `setup.py` file. The version has been incremented from `0.0.13` to `0.0.14`.
* [`setup.py`](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L11-R11): Updated the package version from `0.0.13` to `0.0.14`.
=> Bump version to 0.0.14 in setup.py

anomstack/external/duckdb/duckdb.py, anomstack/external/sqlite/sqlite.py, anomstack/jobs/delete.py, anomstack/main.py, anomstack/sql/read.py, anomstack/sql/translate.py, metrics/defaults/defaults.yaml, metrics/defaults/sql/delete.sql, tests/test_main.py
This pull request introduces several new features and improvements to the `anomstack` project, focusing on database operations and job scheduling. The key changes include the addition of new SQL execution functions for DuckDB and SQLite, the implementation of metric deletion jobs, and the enhancement of the SQL read functionality to handle non-returning queries.
* Added `run_sql_duckdb` function to execute non-returning SQL statements in DuckDB. (`anomstack/external/duckdb/duckdb.py`)
* Added `run_sql_sqlite` function to execute non-returning SQL statements in SQLite with retry logic. (`anomstack/external/sqlite/sqlite.py`)
* Implemented `build_delete_job` function to generate metric deletion jobs and schedules. (`anomstack/jobs/delete.py`)
* Updated `anomstack/main.py` to include the …
=> Add delete job functionality with SQL template and scheduling

setup.py
This pull request includes a small change to the `setup.py` file. The version of the `anomstack` package has been incremented from `0.0.14` to `0.0.15` to reflect updates or bug fixes.
* [`setup.py`](diffhunk://#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L11-R11): Updated the version from `0.0.14` to `0.0.15`.
=> bump version to 0.0.15

metrics/defaults/sql/alerts.sql, metrics/defaults/sql/change.sql, metrics/defaults/sql/dashboard.sql, metrics/defaults/sql/llmalert.sql, metrics/defaults/sql/plot.sql, metrics/defaults/sql/summary.sql
This pull request includes changes to multiple SQL files to standardize the filtering of `metric_timestamp` without converting it to a date. The changes ensure consistency and potentially improve performance by removing unnecessary date conversions.
Changes to SQL files:
* [`metrics/defaults/sql/alerts.sql`](diffhunk://#diff-722ec27fd20334c84a649c0ef8a19b95b3a190d03d148562c1b277574dbe9bfbL23-R23): Updated the `where` clause to filter `metric_timestamp` directly instead of converting it to a date. [[1]](diffhunk://#diff-722ec27fd20334c84a649c0ef8a19b95b3a190d03d148562c1b277574dbe9bfbL23-R23) [[2]](diffhunk://#diff-722ec27fd20334c84a649c0ef8a19b95b3a190d03d148562c1b277574dbe9bfbL46-R46) [[3]](diffhunk://#diff-722ec27fd20334c84a649c0ef8a19b95b3a190d03d148562c1b277574dbe9bfbL64-R64)
* …
=> Optimize SQL queries

metrics/defaults/defaults.yaml, metrics/defaults/sql/score.sql, metrics/defaults/sql/train.sql
This pull request includes changes to the `metrics/defaults` configuration and SQL files to introduce a maximum age for metric timestamps when training and scoring models. The most important changes are summarized below:
Configuration updates:
* [`metrics/defaults/defaults.yaml`](diffhunk://#diff-87b1ac24a54e3a83a9a0c5caddafbc2b2e4c8df4cee00ebfe10c73968112b2f7R23-R26): Added `train_metric_timestamp_max_days_ago` and `score_metric_timestamp_max_days_ago` parameters to limit the age of metric data used for training and scoring.
SQL updates:
* [`metrics/defaults/sql/score.sql`](diffhunk://#diff-91797e236a7f7b1539658334bbc967aec9d74571d8d6b53ad76ee9b8fc96e97aR21-R22): Updated the `where` clause to filter out metric data older than the specified `score_metric_timestamp_max_days_ago` parameter. …
=> Optimize SQL a little more

docs/docs/concepts.md, docs/docs/configuration/metrics.md, docs/docs/data-sources/bigquery.md, docs/docs/data-sources/clickhouse.md, docs/docs/data-sources/duckdb.md, docs/docs/data-sources/motherduck.md, docs/docs/data-sources/python.md, docs/docs/data-sources/redshift.md, docs/docs/data-sources/snowflake.md, docs/docs/data-sources/sqlite.md, docs/docs/data-sources/turso.md, docs/docs/deployment/docker.md, docs/docs/features/alerts.md, docs/docs/features/anomaly-detection.md, docs/docs/features/dashboard.md, docs/docs/features/llm-agent.md, docs/docs/features/metrics.md, docs/docs/intro.md, docs/docs/quickstart.md, docs/sidebars.js
This pull request adds comprehensive documentation for Anomstack, focusing on core concepts, configuration, and support for various data sources. The most significant changes include introducing a detailed overview of Anomstack's core concepts, providing guidance on metrics configuration, and adding dedicated pages for supported data sources.
* [`docs/docs/concepts.md`](diffhunk://#diff-45ed847c57a9f79e6b1b9380539a099e9b73aef6f348e0e907dca517ba11b016R1-R137): Introduced a detailed explanation of Anomstack's core concepts, including metric batches, job types (e.g., ingest, train, score), alerts, dashboards, storage, data sources, configuration, scheduling, and the LLM agent.
* [`docs/docs/configuration/metrics.md`](diffhunk://#diff-6a23a7fca161321edfb58ceac1464d68b7b6c28bb50a0e199960e2728cd …
=> Improve docs

.example.env, Makefile, dagster.yaml, dagster_docker.yaml, docker-compose.yaml, scripts/kill_long_running_tasks.py
- Removed DAGSTER_HOME from .example.env and set it directly in docker-compose.yaml.
- Updated dagster_docker.yaml to enable threading for schedules and sensors with specified worker counts.
- Cleaned up dagster.yaml by uncommenting and consolidating schedule and sensor configurations.
- Enhanced Makefile to streamline local development and added a new target for running Docker in development mode.
- Modified kill_long_running_tasks.py to utilize a configurable timeout for long-running tasks.
This pull request introduces several updates to improve Dagster configuration, Docker setup, and the handling of long-running tasks. The changes standardize environment variable usage, enhance configuration management, and align timeout handling across components.
* Enabled `schedules` and `sensors` …
=> Refactor Dagster configuration and environment setup
